// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to grow your business? Let's discuss custom websites, NFC cards, or early access to our Wallet Pass system."
          primaryButton={{
            text: "Send Message & Get Quote",
            href: "#",
          }}
          secondaryButton={{
            text: "Contact Support",
            href: "mailto:hello@mochasites.com",
          }}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
