// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplit from '@/components/sections/hero/HeroSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplit
          tag="Elevate Your Local Presence"
          title="Turn One-Time Visitors Into Repeat Customers."
          description="Webild websites, 1-tap NFC review & menu cards, and digital wallet loyalty systems designed for local businesses."
          primaryButton={{
            text: "Get a Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Explore NFC Cards",
            href: "#solutions",
          }}
          imageSrc="https://storage.googleapis.com/webild/users/user_3IPz41RWpJWNDIsoCtqQCPjurCH/uploaded-1788316287709-e04ygnt7.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
