// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "how-it-works" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HowItWorksSection(): React.JSX.Element {
  return (
    <div id="how-it-works" data-section="how-it-works">
        <SectionErrorBoundary name="how-it-works">
              <FaqSimple
          tag="Simple Workflow"
          title="How It Works"
          description="Growing your business is easier than you think with our 3-step approach."
          items={[
            {
              question: "Step 1: Setup & Design",
              answer: "We build your high-converting site and configure all your custom NFC cards and print materials.",
            },
            {
              question: "Step 2: Instant Connection",
              answer: "Customers tap your NFC cards or scan posters to instantly view menus, leave reviews, or save your digital pass.",
            },
            {
              question: "Step 3: Automated Growth",
              answer: "Watch your 5-star reviews grow while our system builds an audience of repeat buyers automatically.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
