// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "solutions" section.

import React from 'react';
import FeaturesMediaCards from '@/components/sections/features/FeaturesMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SolutionsSection(): React.JSX.Element {
  return (
    <div id="solutions" data-section="solutions">
        <SectionErrorBoundary name="solutions">
              <FeaturesMediaCards
          tag="Our Solutions"
          title="Growth Tools for Local Business"
          description="Smart, physical-to-digital integrations that bring customers back again and again."
          items={[
            {
              title: "Custom Webild Websites",
              description: "Speed-optimized, mobile-friendly landing pages built to drive phone calls, bookings, and foot traffic.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3IPz41RWpJWNDIsoCtqQCPjurCH/uploaded-1788316897989-0qgmzxdn.png",
            },
            {
              title: "Smart NFC Cards",
              description: "Instant 1-tap cards for Google Reviews, digital menus, or opening your website without typing URLs.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3IPz41RWpJWNDIsoCtqQCPjurCH/uploaded-1790698605161-f6wf3q4r.jpg",
            },
            {
              title: "Custom Posters & Print",
              description: "High-impact physical posters and table-tents integrated with QR and NFC technology for maximum conversion.",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3IPz41RWpJWNDIsoCtqQCPjurCH/uploaded-1790698689006-set49v3k.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
