// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "solutions" section.

import React from 'react';
import FeaturesMediaCards from '@/components/sections/features/FeaturesMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SolutionsSection(): React.JSX.Element {
  return (
    <div id="solutions" data-section="solutions">
        <SectionErrorBoundary name="solutions">
              <FeaturesMediaCards
          tag="Our Solutions"
          title="Growth Tools for Local Business"
          description="Smart, physical-to-digital integrations that bring customers back again and again."
          items={[
            {
              title: "Custom Webild Websites",
              description: "Speed-optimized, mobile-friendly landing pages built to drive phone calls, bookings, and foot traffic.",
              imageSrc: "http://img.b2bpic.net/free-photo/modern-smartphone-with-live-abstract-wallpaper-coming-out-screen_23-2151033636.jpg",
            },
            {
              title: "Smart NFC Cards",
              description: "Instant 1-tap cards for Google Reviews, digital menus, or opening your website without typing URLs.",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-young-female-courier-blue-uniform-black-gloves-black-mask-holding-phone-white-card_140725-23459.jpg",
            },
            {
              title: "Custom Posters & Print",
              description: "High-impact physical posters and table-tents integrated with QR and NFC technology for maximum conversion.",
              imageSrc: "http://img.b2bpic.net/free-photo/high-angle-hand-holding-device_23-2149340927.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
