/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { cls } from "@/lib/utils";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";

const primaryButton = {
  text: "Join the Beta Waitlist",
  href: "#contact"
};
const metrics = [
  {
    value: "1-Tap Pass",
    title: "Frictionless Savings",
    description: "Instant add-to-wallet digital passes for Apple Wallet & Google Pay."
  },
  {
    value: "100% Auto",
    title: "Automated Messaging",
    description: "Push notifications, lock-screen updates, and personalized rewards."
  },
  {
    value: "+40% Retention",
    title: "Repeat Foot Traffic",
    description: "Turn one-time customers into regular repeat buyers automatically."
  }
];

type Metric = {
  value: string;
  title: string;
  description: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const WalletTeaserInline = () => (
  <section aria-label="Metrics section" className="py-20">
    <div className="flex flex-col gap-8 md:gap-10">
      <div className="flex flex-col items-center gap-2 w-content-width mx-auto">
        <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
          <p>{"Beta Access"}</p>
        </div>

        <TextAnimation
          text={"1-Tap Apple Wallet Loyalty System"}
          variant={"fade-blur"}
          gradientText={true}
          tag="h2"
          className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
        />

        <TextAnimation
          text={"When a customer taps your card, a digital loyalty card is saved straight into their wallet. Automate engagement and bring them back."}
          variant={"fade-blur"}
          gradientText={false}
          tag="p"
          className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
        />

        {(primaryButton || undefined) && (
          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            {primaryButton && <Button text={primaryButton.text} href={primaryButton.href} variant="primary"/>}
            {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-content-width mx-auto">
        {metrics.map((metric) => (
          <ScrollReveal
            variant="slide-up"
            key={metric.value}
            className="flex flex-col justify-between gap-4 p-6 xl:p-8 card rounded min-h-[220px]"
          >
            <span className="text-4xl md:text-5xl font-semibold leading-snug">{metric.value}</span>
            <div className="flex flex-col gap-2 min-w-0">
              <span className="text-xl md:text-2xl font-semibold">{metric.title}</span>
              <div className="w-full h-px bg-accent" />
              <p className="text-base leading-snug">{metric.description}</p>
            </div>
          </ScrollReveal>
        ))}
      </div>
    </div>
  </section>
);

export default function WalletTeaserSection() {
  return (
    <div data-webild-section="wallet-teaser" data-section="wallet-teaser" id="wallet-teaser">
      <WalletTeaserInline />
    </div>
  );
}
