// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "wallet-teaser" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WalletTeaserSection(): React.JSX.Element {
  return (
    <div id="wallet-teaser" data-section="wallet-teaser">
        <SectionErrorBoundary name="wallet-teaser">
              <MetricsMediaCards
          tag="Beta Access"
          title="1-Tap Apple Wallet Loyalty System"
          description="When a customer taps your card, a digital loyalty card is saved straight into their wallet. Automate engagement and bring them back."
          primaryButton={{
            text: "Join the Beta Waitlist",
            href: "#contact",
          }}
          metrics={[
            {
              value: "1-Tap",
              title: "Frictionless Savings",
              description: "Instant add-to-wallet.",
              imageSrc: "http://img.b2bpic.net/free-photo/army-soldier-reviews-targets-satellite-world-map-ensure-global-protection_482257-91236.jpg",
            },
            {
              value: "",
              title: "Automated",
              description: "personalized",
              imageSrc: "http://img.b2bpic.net/free-photo/email-alert-popup-reminder-concept_53876-123868.jpg",
            },
            {
              value: "Retention",
              title: "Repeat Foot Traffic",
              description: "Building loyal audiences.",
              imageSrc: "http://img.b2bpic.net/free-photo/finger-indicating-graph-rises_1134-103.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
